parameters:
  hg38:
    index: "/Users/alderc/1-projects/12-GSTT/2-Data/1-Ref/hg38.mmi"
  dir: "Test"
  centrifuge:
    index: "/Users/alderc/1-projects/12-GSTT/1-Project/2-metagenomics/Pilot/index_hpvc/hpvc"
    tree: "/Users/alderc/1-projects/12-GSTT/1-Project/2-metagenomics/Pilot/index_hpvc/hpvc.tree"
    names: "/Users/alderc/1-projects/12-GSTT/1-Project/2-metagenomics/Pilot/index_hpvc/hpvc.names"
taxonomy:
  names: "/Users/alderc/1-projects/12-GSTT/2-Data/Taxonomy/taxdmp_2020-04-01/names.dmp"
  nodes: "/Users/alderc/1-projects/12-GSTT/2-Data/Taxonomy/taxdmp_2020-04-01/nodes.dmp"
  refseqDir: "/Users/alderc/1-projects/12-GSTT/2-Data/Taxonomy/refseq_genomes/"
  speciesFileNames: "ref/metag_assembly_data.txt"
  speciesTaxMeta: "/Users/alderc/1-projects/12-GSTT/2-Data/Taxonomy/metag_assembly_summary.txt"
scagaire: "ref/scagaire_genes.txt"


