samples: "sample_table.tsv"
move: true 
data_dir: "/home/cja/1-projects/1-CMg/test"
time: [2]
abundance_threshold: 1
cfg_score: 8000
targets: "ref/target_organisms.txt"
parameters:
  hg38:
    index: "ref/hg38/hg38_new.mmi"
  centrifuge:
    index:
      cmg: "ref/centrifuge_idx/bacterial/cmg_pilot_phase3"
      viral: "ref/centrifuge_idx/viral/cmg_viral"
taxonomy:
  dictFile: "ref/refseq/Assembly_summary/argos_taxdict.tsv"
  names: "ref/refseq/taxonomy/names.dmp"
  nodes: "ref/refseq/taxonomy/nodes.dmp"
  refseqDir: "ref/refseq/genomes/" # Changed to test argos
  speciesFileNames: "ref/refseq/Assembly_summary/metag_filepaths.txt"
  speciesTaxMeta: "ref/refseq/Assembly_summary/combined_assembly_summary.txt"
amr:
  scagaire: "ref/scagaire_genes.txt"
viral:
  targets: "ref/viral/viral_targets.tsv"
mlst:
  directory: "ref/pubmlst/"
  list: "ref/pubmlst/mlst_organisms.tsv"
pdf:
  html: "ref/Template/report_template.html"
  css: "ref/Template/report.css"
  bootstrap: "ref/Template/bootstrap.css"
    


