parameters:
  time: 1
  hg38:
    index: "ref/hg38/hg38.mmi"
  dir: "Test"
  centrifuge:
    index: "ref/index_reference_qnap/metag_ref"
taxonomy:
  names: "ref/refseq/taxonomy/names.dmp"
  nodes: "ref/refseq/taxonomy/nodes.dmp"
  refseqDir: "ref/refseq/Genomes/"
  speciesFileNames: "ref/refseq/Assembly_summary/metag_filepaths.txt"
  speciesTaxMeta: "ref/refseq/Assembly_summary/combined_assembly_summary.txt"
scagaire: "ref/scagaire_genes.txt"



