samples: "sample_table.tsv"
time: [0.5,2,16]
abundance_threshold: 0.75
cfg_score: 8000
parameters:
  hg38:
    index: "ref/hg38/hg38_new.mmi"
  centrifuge:
    index: "ref/Cmg_index/pilot_cmg"
taxonomy:
  dictFile: "ref/refseq/Assembly_summary/argos_taxdict.tsv"
  names: "ref/refseq/taxonomy/names.dmp"
  nodes: "ref/refseq/taxonomy/nodes.dmp"
  refseqDir: "ref/refseq/genomes/" # Changed to test argos
  speciesFileNames: "ref/refseq/Assembly_summary/metag_filepaths.txt"
  speciesTaxMeta: "ref/refseq/Assembly_summary/combined_assembly_summary.txt"
amr:
  scagaire: "ref/scagaire_genes.txt"
pdf:
  html: "ref/Template/report_template.html"
  css: "ref/Template/report.css"
  bootstrap: "ref/Template/bootstrap.css"
    


