parameters:
  hg38:
    index: "ref/hg38/hg38.mmi"
  centrifuge:
    index: "ref/Cmg_index/Cmg"
taxonomy:
  names: "ref/refseq/taxonomy/names.dmp"
  nodes: "ref/refseq/taxonomy/nodes.dmp"
  refseqDir: "ref/refseq/Genomes/"
  speciesFileNames: "ref/refseq/Assembly_summary/metag_filepaths.txt"
  speciesTaxMeta: "ref/refseq/Assembly_summary/combined_assembly_summary.txt"
amr:
  scagaire: "ref/scagaire_genes.txt"
  template: "ref/scagaire_template.txt"
    



